### ISSUE TITLE
Kernel Null on start up when WatchUpdateTimer_Tick runs

### ISSUE THREAD

**Issue by shoulderrats** [Trinity-11/FoenixIDE#11]
Some times when I start up the FoenixIDE, it immediately throws a kernel null error. It happens before the select kernel dialog appears. I found a little work around, though I think it is just a case of the timer starting before a kernel is chosen successfully. My work around is:

C:\git\FoenixIDE\Main\UI\WatchForm.cs
private void WatchUpdateTimer_Tick(object sender, EventArgs e)
{
	if (kernel == null) return; //avoid null kernel error in foreach loop below._

	foreach (KeyValuePair<int, WatchedMemory> kvp in kernel.WatchList)

**Comment by dtremblay** [comment]
Thanks for reporting the bug.
This has been fixed in release 0.4.1.9.
