### ISSUE TITLE
 TAX, TAY, TSX and others should set N and Z flags

### ISSUE THREAD

**Issue by aniou** [Trinity-11/FoenixIDE#14]
According to manual and available docs: http://www.6502.org/tutorials/65c816opcodes.html#6.10.1 TAX, TAY, TSX, TXA, TXY, TYA  and TYX should set NZ flags (depending of X/M flags and direction of transfer).

Lack of that prevents my port of [of816 Forth](https://github.com/aniou/of816/tree/C256/platforms/C256), [fresh hex file here](http://smutek.pl/65c816/forth.hex) from working - after cursory correction of TAY behavior all problems were gone.

Unfortunately, I don't have a production-ready code at this moment, so no patch provided.

**Comment by dtremblay** [comment]
I'm also surprised to find that the emulator was not setting any of the CPU flags.

I've added a unit test to cover the example provided in the the URL you provided.

This is included in release-0.5.2.2 of the IDE.
