### ISSUE TITLE
Unable to flash my FMX RevC4 with a new kernel

### ISSUE THREAD

**Issue by randyrossi** [Trinity-11/FoenixIDE#15]
I tried to flash the latest kernel to my FMX RevC4 board but am now getting a black screen.  

Problem 1: Selecting a kernel.hex in the uploader prevents me from checking the 'flash' checkbox.  So I had to select a .bin file, then check it, then select the .hex file before flashing would take effect.

Problem 2: Stefanie's video says the kernel should be 512k but the kernel.hex shows up as nearly 4Mb.  Does the provided kernel.hex in the IDE repo work on the real FMX board?  If not, where is the kernel that came with my device?

Problem 3: It was unclear what destination address I should set when I perform a flash.  The online docs say 38:0000 but Stefanie's video says to leave it as 00:0000.  Which is correct?

After several attempts, I now get a black screen on boot.  At one point, I was able to go back to the kernel found in the separate kernel repository but have not been able to do that again.  Can you describe the process you use to flash your FMX board with the latest kernel?  Did I overwrite something important in a different location or can I restore my board to a working state?  Thanks.

**Comment by randyrossi** [comment]
Closing this.  I was flashing the wrong kernel and I guess the kernel found in the IDE does not work with the real board.

**Comment by dtremblay** [comment]
The kernel.hex provided in the IDE is the same one that's flashed in the FMX RevC of the board.
