### ISSUE TITLE
Installer produces a shortcut in Start menu which doesn't work

### ISSUE THREAD

**Issue by vinz6751** [Trinity-11/FoenixIDE#18]
To reproduce: install the IDE with "Just for me", or for all users. 
Look the produced link: 
For just me, the target file is e.g. "C:\Users\Vincent\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"
For all users, the target file is .e.g "C:\ProgramData\Microsoft\Windows\Start Menu\Programs"

But it seems it should point to the actual exe.

**Comment by dtremblay** [comment]
I thought I had removed the Start Menu shortcut.  It didn't work for me either, on Windows 10.

Did the shortcut on your desktop work?

**Comment by dtremblay** [comment]
I've pushed a new release: 0.5.5.3, which fixes this issue.

See: https://github.com/Trinity-11/FoenixIDE/releases/tag/release-0.5.5.3

Also, I've started adding notes for the Game Generator here: https://github.com/Trinity-11/FoenixIDE/wiki/Game-Generator-Editor

**Comment by vinz6751** [comment]
Yes Daniel, the desktop shortcut works. Thanks for fixing the issue so quickly!
