### ISSUE TITLE
File open error

### ISSUE THREAD

**Issue by GertLeusink** [Trinity-11/FoenixIDE#19]
There is a full path in gameformdesigner.cs in line 92, this should be a relative path like; this.CodeTextBox.DescriptionFile = @".\Resources\foenix-game-generator-syntax.xml"; also the resource file should have a property to be copied if newer so that it is included when running debugging.

**Comment by dtremblay** [comment]
The change for the relative filepath breaks the from designer.  The other change was already committed several days ago.

You should use the MSI installer to run the Foenix IDE.
