### ISSUE TITLE
Support for .bin files

### ISSUE THREAD

**Issue by clandrew** [Trinity-11/FoenixIDE#25]
Looks like only Intel hex based programs are natively supported right now.

**Comment by dtremblay** [comment]
A bin file is just raw binary.  So it's not Intel specific.  You can only provide one start address.

**Comment by clandrew** [comment]
That's not the correct understanding of my text. ["Intel hex"](https://en.wikipedia.org/wiki/Intel_HEX) is the term for the format the emulator currently supports

**Comment by dtremblay** [comment]
The IDE currently supports .hex, .pgz and .pgx files.  I'll be adding the .bin files to the "Open Executable File" dialog, with a prompt for "Enter Bin Start Address".

**Comment by dtremblay** [comment]
This was added in release 0.6.0.9.
