### ISSUE TITLE
Crash during "Convert HEX to PGX"

### ISSUE THREAD

**Issue by clandrew** [Trinity-11/FoenixIDE#26]
Use this .hex file below for repro:

:02FFFC000020E3
:2020000018FBE220C210A90048ABA21420221C1000EA80FD48656C6C6F2C2074686973209A
:0C2020006973206120746573742E0D003C
:00000001FF

Source code available here: 
https://github.com/clandrew/fnxapp/blob/main/hello/hello.s

![image](https://github.com/Trinity-11/FoenixIDE/assets/8118775/55498cda-c050-4c10-aba4-92a37ee98b44)

**Comment by dtremblay** [comment]
I've reproduced the defect.  It was easy enough. Thanks for submitting the issue.

**Comment by clandrew** [comment]
glad to hear, and no problem!

**Comment by dtremblay** [comment]
This is a tricky hex file... usually the lines in one block are consecutive.  The hex loader doesn't keep track of blocks to figure out how to write the PGX segments. I'll have to stew on this for a bit to figure out how I want to implement this.

**Comment by clandrew** [comment]
Makes sense to pop up an error message, it's not possible to have a PGX with multiple segments

**Comment by dtremblay** [comment]
An alert is now shown if the Hex requires multiple segments - which means it is not a good fit for PGX.

**Comment by clandrew** [comment]
Great!
