### ISSUE TITLE
F256, Boot To Flash or RAM?

### ISSUE THREAD

**Issue by noyen1973** [Trinity-11/FoenixIDE#28]
The first group of developmental F256JRs had a software setting for whether the F256 boots in Flash or RAM mode and the rest of the mini ITX  versions of the JR had a hardware jumper.  The F256K returned to a software setting for the boot mode.  Any plans for a setting in the IDE's Upload Tool for the boot mode when it comes to the F256?

**Comment by dtremblay** [comment]
I didn't know about this. I'll have a look into it. Using the DIP switches was how I dealt with this in the FMX.

**Comment by dtremblay** [comment]
This was implemented in release 0.7.0.0.
