### ISSUE TITLE
incomprehensible behavior of Direct Page register?

### ISSUE THREAD

**Issue by aniou** [Trinity-11/FoenixIDE#4]
Recently I played a little around [passing arguments via stack](http://6502org.wikidot.com/software-65816-parameters-on-stack) and I found behaviour that embarrasses me. It is possible that root cause comes from my lack of experience, but bahvior is different between FoenixIDE and [c256emu](https://npm.pkg.github.com/rdaum/c256emu), so I decide to fill this issue.

All that I want was a trick with setting DirectPage register to current stack position and got values from stack using direct-page LDA commands (as LDA 10, LDA 8 etc).  Below is heavily-annotated source of my sample program, that loads at $03:0000

```asm
.cpu "65816"			
.include "macros_inc.asm"

			* = $030000
		
			CLC					; clear the carry flag
			XCE					; move carry to emulation flag.
			setaxl
			
                        pea #$1234          ; first argument
			tsc                 ; pointer to first argument 
			inc a
			pha                 ; address of first pointer to stack
			pea #$4567          ; second argument
			pea #$89ab          ; third argument
			jsr test           
			
		
 
 test		phd                 ; presere Direct on stack / FoenixIDE: 0000 rdaum/c256emu: pointer
			tsc                 ; current stack position
			inc a               
			tcd                 ; stack position to direct register

			; D points to one past our return address, so we may now refer
			; to our inputs via direct page references.

			; at this moment stack on FoenixIDE looks like (c256emu is almost the same)
			; FEFF 12
			; FEFE 34 - first value
			; FEFD FE  
			; FEFC FE - stack pointer
			; FEFB 45
			; FEFA 67 - second value
			; FEF9 89
			; FEF8 AB - third value
			; FEF7 00
			; FEF6 13 - return addr 
			; FEF5 00
			; FEF4 00 - Direct Reg preserve ($fef4 on c256emu)
			; Direct Register = $FEF4
			; DBR             = $00
			
                                ; expect and got on rdaum/c256emu | GOT val on FoenixIDE:
                        lda 10     ; expect $1234 | GOT $1234                         
			lda 8       ; expect stack pointer (example $fef2) | GOT $fefe
			lda 6       ; expect $4567 | GOT $0013 - return pointer 
			lda 4       ; expect $89ab | GOT $0000 ??? 
			lda 2       ; expect return pointer (example $0012) | GOT $0013
			lda 0       ; expect Direct reg ($fef4) | GOT $0000 - but see below

					
			lda #$9988
			sta 10
			lda #$7766
			sta 8
			lda #$5544
			sta 6
			lda #$3322
			sta 4
			lda #$11aa
			sta 2
			lda #$bbcc
			sta 0

			; at this moment stack on FoenixIDE looks like (
                        ; c256emu was consistent with lda/sta sequence)
			; look at fefb, fefa, fef9, fef8 - 
			; FEFF 99
			; FEFE 88
			; FEFD 77
			; FEFC 66
			; FEFB 45 - should be 55 like in c256emu?
			; FEFA 67 - should be 44 ... ?
			; FEF9 89 - should be 33 ... ?
			; FEF8 AB - should be 22 ... ?
			; FEF7 11
			; FEF6 aa
			; FEF5 bb
			; FEF4 cc
			; Direct Register = $FEF4
			; DBR             = $00


                        lda 10              ; expect $9988 - ok
			lda 8               ; expect $7766 - ok
			lda 6               ; expect $5544 GOT $11aa in FoenixIDE
			lda 4               ; expect $3322 GOT $bbcc  ...
			lda 2               ; expect $11aa GOT $11aa  ...
			lda 0               ; expect $bbcc GOT $bbcc  ...
			
            brk
```

**Comment by aniou** [comment]
As update: direct memory access in FoenixIDE gave me correct values, ie.:

```asm

; Direct register set to $fef4

lda 6       ; expect $4567 | GOT $0013 - return pointer
lda $fefa   ; got $4567 as expected 

sta 6       ; doesn't change data under $fefa
sta $fefa   ; works, stack memory was changed
```

**Comment by rdaum** [comment]
Ok looking at the FoenixIDE sources, I believe direct page address calculations are wrong in Register.cs line 310:

return this.Value | (address & 0Xff);

This would only work if the direct page was aligned on 256 byte boundaries ($xx00). However this is not how a 65816 behaves, as per "Programming the 65816" Page 199:

"the direct page does not have to start on a page boundary; the direct page register can hold any sixteen-bit value."

So in the case of DP == $FEF4, FoenixIDE is doing this:

LDA 7  reads from 0xfef4 | 7, giving 0xfef7

but should probably be doing

(0xfef4 + 7) & 0x0000ffff == $fefb

I don't think this fully explains how aniou is getting the values they're getting though. But they did confirm (in chat) that things behave correctly once DP is aligned on an even 256 byte boundary.

For reference, this is how c256emu's core calculates direct page addresses:

https://github.com/achaulk/retro_cpu/blob/master/cpu/65816/cpu_65c816_instructions.inl#L431

Note there are some intricacies for emulation mode and the like but the core of it should be a simple addition.

**Comment by aniou** [comment]
I made some checks with different stack locations and got following results - in some cases same memory areas were overwritten by two consecutive STA. Current A value in parentheses.

In summary: when stack starts from $F2FF or $F2FE results were wrong - when starts from $F2FC - correct.

```
Top: $F2FF
SP : $F2F3
D  : $F2F4
N  :   12
───────────
F2FF 99      
F2FE 88      sta 10 ($9988)
F2FD 77
F2FC 66      sta 8  ($7766)
F2FB 45
F2FA 67
F2F9 89
F2F8 11
F2F7 55                       then  aa  by sta 2 ($11aa)      
F2F6 44      sta 6  ($5544)
F2F5 33                             bb
F2F4 22      sta 4  ($3322)   then  cc  by sta 0 ($bbcc)


Top: $F2FE
SP : $F2F2
D  : $F2F3
N  :   12
───────────
F2FE 12      
F2FD 34      
F2FC 99                           77
F2FB 88      sta 10 ($9988) then  66 by sta 8 ($7766)
F2FA 45
F2F9 67
F2F8 55                           33
F2F7 44      sta 6  ($5544) then  22 by sta 4 ($3322)
F2F6 FF
F2F5 FF
F2F4 11                           bb
F2F3 aa      sta 2  ($11aa) then  cc by sta 0 ($bbcc)



Top: $F2FC
SP : $F2F0
D  : $F2F1
N  :   12
───────────
F2FC 99
F2FB 88     sta 10 ($9988)
F2FA 77  
F2F9 66     sta 8  ($7766)
F2F8 55
F2F7 44     sta 6  ($5544)
F2F6 33
F2F5 22     sta 4  ($3322)
F2F4 11
F2F3 AA     sta 2  ($11aa)
F2F2 BB
F2F1 CC     sta 0  ($bbcc)
```

**Comment by dtremblay** [comment]
Thank you for pointing me to this error.  I've found that the direct page address was "OR"ed with the signature value, and this is incorrect.  This works fine when the bank register is used but not for Direct Page addressing.

I'll keep going through your code to see if there are other similar problems.
I'll push a commit today.

Cheers!

**Comment by dtremblay** [comment]
I"ve pushed release 0.2.3.5 to correct this issue and an issue with Absolute Indexed with Y addressing.
I've tested with different values of the stack, as well.
