### ISSUE TITLE
(SD Card emulation) Endless looping directory listing 

### ISSUE THREAD

**Issue by Mu0n** [Trinity-11/FoenixIDE#44]
Using the new feature for SD card in the menu Tools/SD Card, using these default settings:
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/3879f8b3-b80e-4c46-b9af-fb397980bfd3)
(Enabled SD Card: checked, A folder inside my host PC is selected. Capacity: 64 MB, Cluster: 512, Type: FAT32)

I get an odd behavior whenever I try to list the directory. This happens in both dos and in superbasic. The directory will endlessly loop back from the beginning as it lists the file. This happens only when you reach 15 items or more present in the chosen directory. You can break the loop in DOS by hitting CTRL-C, but you can't do likewise in superbasic (it just silently continues to list its endless loop and ignores your break command keystroke).

This is a screencap after such a break issued while the bug is happening in dos:
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/637c3ee9-c628-45c6-9dc4-a0a14bfc97c8)

**Comment by dtremblay** [comment]
Fix for this defect is in release 0.6.0.20.
