### ISSUE TITLE
Wrong NativeWidth leads to "horizontally fat pixels"

### ISSUE THREAD

**Issue by Mu0n** [Trinity-11/FoenixIDE#45]
### Cause and Symptoms

In Main/Display/Gpu.cs (https://github.com/Trinity-11/FoenixIDE/blob/master/Main/Display/Gpu.cs)
there exists two public int constants: NativeWidth and NativeHeight which are set to 768 and 480 respectively.

However, every Foenix machines has only ever needed this set of possible resolutions:
640x480
640x400
800x600
1024x768 
(source: Stefany Allaire herself!)

The result leads to horizontally stretched images such as this test pattern where the screen is filled with the lower case letter l. You will see that some columns of the letter l are slightly wider than others:
(this is under scaling 2.0x) - click on the image thumbnail to see the 100% real state of it
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/d85ad6f4-85ca-42bf-a2b5-a6ce28f0fcc3)

If you change NativeWidth from 768 to the correct 640, you get this image where every letter is perfectly identical (this should be the desired end result) - click on the image thumbnail to see the 100% real state of it
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/da274dad-7ed6-4951-9524-4108970dc9a6)

Testing it under Livingworlds.pgz, we get the incorrect 768x480 stretched version:
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/a8cd3d21-bf47-472d-abdf-7f05581111e8)

Followed by the correct 640x480 version:
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/5d001149-6695-41a0-a495-d1354e287860)

**Comment by Mu0n** [comment]
### Proposed solution
I've forked the project here: https://github.com/Mu0n/FoenixIDE

I propose to add more menu items to accomodate the two main resolutions of the F256Jr and F256K line of computers, but it can easily be extended to the other previously mentioned resolutions. I'm not aware of how much the other machines are receiving attention, but I'll choose not to assume anything and leave it open for more easily added choices to accomodate them.

In my fork, I padded the scaling menu with more options:
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/b426b236-4231-4de3-ae2f-0e5e2a16d307)

Instead of using public int constants for being at the base of the scaling choices which acts great for one use case but not for the others, I just let the decision happen inside the menu item click event methods themselves and added width and height parameters to the SetViewScaling method in gpu.cs.

This is an example for the 640x400 pixels running at 70 Hz which gives the F256's a 80x50 text resolution. You set bit 0 (CLK_70) to 1 at address $D001 to enable that mode. I chose scaling 2.0x and it's all showing at perfect unstretched squares, which you could not get before, unless you were really patient and set by changing the size of your window manually at the exact right dimensions (!):
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/7072d0da-adda-4785-87d3-334616fa80bb)

### Remaining issues

The 1.0X scaling is problematic at both 640x480 and 640x400 modes, because the UI of the emulator forces the window to be at least 669 pixels at the very least, which forces the ClientRectangle to follow suit with the Form size and become too large horizontally.

The 1.5X scaling shows a slight stretch and I'm unsure why. Example (at 640x480, $D001 bit set to 0 for 60Hz):
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/76a4b2f8-f537-4f85-be1a-7c12722288a2)

**Comment by dtremblay** [comment]
If you have something that works, please submit a Pull Request.  Thanks!

**Comment by Mu0n** [comment]
Thank you! I will once I figure it out. I'm befuddled by the 1.5x scaling.

My first attempt will be to break down the bottom status thingies into 2 rows instead of one so that the minimum width of the window can reach 640 pixels wide instead of 669.

**Comment by dtremblay** [comment]
I think this can finally be closed.  Fixed in release 0.6.0.21.
