### ISSUE TITLE
(SD Card Emulation) File storage error while accessing files with more than 3 letters in the extension

### ISSUE THREAD

**Issue by Mu0n** [Trinity-11/FoenixIDE#48]
the current sd card functionality doesn't seem to support file extensions above 3 letters
I tried to load Enersto's dice roller basic program: 
https://ptb.discord.com/channels/691915291721990194/988706842685345793/1165093964601372704
here, it fails to load the dice20b.bspr file 

![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/ac78d6a0-7dad-4675-b976-cb8c79df7174)
after editing that line and changing the file extension to 3 letters only, it loads fine
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/62276738-4c78-48f5-993b-7723b579eefc)

Here are the settings I'm using in the sd card emulation dialog:
![image](https://github.com/Trinity-11/FoenixIDE/assets/6774826/0a8941ef-79f5-455e-acaa-4eae5436e8e7)

**Comment by dtremblay** [comment]
Added VFAT long file names to address this issue, in release 0.6.0.20.
