### ISSUE TITLE
XBA (0xEB) opcode not implemented

### ISSUE THREAD

**Issue by aniou** [Trinity-11/FoenixIDE#5]
Hi,
following code causes FoenixIDE emulator crash with error: "System.NotImplementedException: ExecuteMisc() opcode not implemented: EB"

[XBA description](http://www.6502.org/tutorials/65c816opcodes.html#6.10.3)

```asm

             CLC
	     XCE
             setal
             lda #$1234
             xba

```

**Comment by dtremblay** [comment]
Thanks for your input.  I've updated the XBA opcode in release 0.2.3.6.

Dan
