### ISSUE TITLE
Uploader packet size should be readjusted lower for F256 family

### ISSUE THREAD

**Issue by Mu0n** [Trinity-11/FoenixIDE#54]
For F256K and F256Jr modes, from Stefany:

when there is a transfer being done, the read and write packets needs to be smaller, because the internal memory to receive and send them packets are smaller. I believe that in bigger machine the Rx/Tx buffer is 8K, but in the F256x line it is only 2K... So some changes would required to support that.

**Comment by dtremblay** [comment]
I'm surprised nobody else has mentioned this before.  What took so long?

**Comment by dtremblay** [comment]
Fixed in release 0.6.0.21.
