### ISSUE TITLE
LDA/LDX/LDY doesn't set N for 16-bit values

### ISSUE THREAD

**Issue by aniou** [Trinity-11/FoenixIDE#7]
Looks like LDA, LDX and LDY doesn't set N flag when highest bit of 16-bit value is set.
They works properly in 8-bit mode, though. 

I tried immediate and direct modes.

```asm
clc
xce
setaxl
lda #%1000_0000_0000_0000        ; N = 0, should be 1
ldx #%1000_0000_0000_0000        ; N = 0, should be 1
ldy #%1000_0000_0000_0000        ; same as above
```

**Comment by dtremblay** [comment]
Thank you, I've confirmed your findings.  And I've found the defect.

Release 0.2.3.7 contains the fix.

Cheers!

Dan
