### ISSUE TITLE
open hex file w/o zeroing resets cpu state

### ISSUE THREAD

**Issue by aniou** [Trinity-11/FoenixIDE#8]
Currently reading hex file with "File -> open w/o zeroing" resets CPU state: 

![obraz](https://user-images.githubusercontent.com/825100/61597379-5eb6c000-ac10-11e9-906d-0a4a6f23ea58.png)

In my opinion preserving registers, flags etc. will be useful during testing code snippets - and if reset is needed, there is even option for that.

**Comment by dtremblay** [comment]
This defect is more than 5 years old and has not be requested by others.
