### ISSUE TITLE
ExecuteLDX and ExecuteLDY function incorrect

### ISSUE THREAD

**Issue by bzuidgeest** [Trinity-11/FoenixIDE#9]
In file operations.cs there is a bug with ExecuteLDX and ExecuteLDY. They set N and Z based on the A register and not the X or Y register respectively. This is different from aniou's earlier issue.

 public void ExecuteLDX(byte instruction, AddressModes addressMode, int signature)
        {
            int val = GetValue(addressMode, signature, cpu.X.Width);
            cpu.X.Value = val;
            **cpu.Flags.SetNZ(cpu.A);**
        }

        public void ExecuteLDY(byte instruction, AddressModes addressMode, int signature)
        {
            int val = GetValue(addressMode, signature, cpu.Y.Width);
            cpu.Y.Value = val;
            **cpu.Flags.SetNZ(cpu.A);**
        }

Should be:

 public void ExecuteLDX(byte instruction, AddressModes addressMode, int signature)
        {
            int val = GetValue(addressMode, signature, cpu.X.Width);
            cpu.X.Value = val;
            **cpu.Flags.SetNZ(cpu.X);**
        }

        public void ExecuteLDY(byte instruction, AddressModes addressMode, int signature)
        {
            int val = GetValue(addressMode, signature, cpu.Y.Width);
            cpu.Y.Value = val;
            **cpu.Flags.SetNZ(cpu.Y);**
        }

I found this by comparing the execution to the WDC simulator/debugger.

p.s. ( I also noted this on the discord )

**Comment by dtremblay** [comment]
Thank you.  I've made the change in the Foenix IDE release 0.2.4.2.
